server {
    listen       80;
    server_name  typecho.qy;

    location / {
        root   /usr/share/nginx/html;
        index  index.php index.html index.htm ;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;
        fastcgi_param PATH_INFO $path_info;
        # try_files $fastcgi_script_name =404;
        # fastcgi_param SCRIPT_FILENAME /var/www/html/blog/$fastcgi_script_name;
        fastcgi_param SCRIPT_FILENAME /www/$fastcgi_script_name;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # location ~ \.php {
    #     fastcgi_pass   php:9000;
    #     fastcgi_index  index.php;
    #     fastcgi_param  SCRIPT_FILENAME  /www/$fastcgi_script_name;
    #     include        fastcgi_params;
    # } 
}
